name: Generate code coverage badge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Update coverage badge
    steps:
    - name: Test
      run: go test -v ./...

    - name: Update coverage report
      uses: ncruces/go-coverage-report@main
      if: |
        matrix.os == 'ubuntu-latest' &&
        github.event_name == 'push'
      continue-on-error: true